spring.datasource.url=jdbc:mysql://localhost:3306/aftas?zeroDateTimeBehavior=convertToNull
spring.datasource.username=root
spring.datasource.password=0000
spring.liquibase.change-log=classpath:db/changelog-master.xml
spring.jpa.hibernate.ddl-auto=none
